# Generated by Django 3.0.7 on 2020-06-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('FullName', models.TextField()),
                ('About_me_Home', models.TextField()),
                ('Job_Title', models.CharField(max_length=32)),
                ('About_me_About', models.TextField()),
                ('Birthday', models.CharField(max_length=16)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=256)),
                ('MobileNumber', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.TextField()),
                ('institute_name', models.TextField()),
                ('year_of_education', models.TextField()),
                ('about_education', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile_details')),
            ],
        ),
    ]
