# Generated by Django 3.0.7 on 2020-06-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_details',
            name='About_me_About',
        ),
        migrations.RemoveField(
            model_name='profile_details',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='profile_details',
            name='Birthday',
        ),
        migrations.RemoveField(
            model_name='profile_details',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='profile_details',
            name='FullName',
        ),
        migrations.RemoveField(
            model_name='profile_details',
            name='Job_Title',
        ),
        migrations.RemoveField(
            model_name='profile_details',
            name='MobileNumber',
        ),
        migrations.CreateModel(
            name='about_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=32)),
                ('Job_details', models.TextField()),
                ('About_me_About', models.TextField()),
                ('Degree', models.CharField(max_length=32)),
                ('Birthday', models.CharField(max_length=16)),
                ('Freelance', models.CharField(max_length=32)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=256)),
                ('MobileNumber', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile_details')),
            ],
        ),
    ]
