# Generated by Django 3.0.7 on 2020-06-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_auto_20200626_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_details',
            name='City',
            field=models.CharField(default='Bangalore', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_details',
            name='Website',
            field=models.TextField(default='https://resumeaayush.herokuapp.com/'),
            preserve_default=False,
        ),
    ]
