# Generated by Django 3.0.7 on 2020-06-27 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_auto_20200626_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='professional_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=56)),
                ('year_of_work', models.CharField(max_length=56)),
                ('company_name', models.CharField(max_length=56)),
                ('about_work', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile_details')),
            ],
        ),
    ]
