# Generated by Django 3.0.7 on 2020-06-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0006_professional_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_details',
            name='MobileNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='social_profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.TextField()),
                ('facebook', models.TextField()),
                ('instagram', models.TextField()),
                ('linkedin', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile_details')),
            ],
        ),
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=32)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile_details')),
            ],
        ),
    ]
