# Generated by Django 3.0.7 on 2020-06-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0007_auto_20200628_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_name',
        ),
        migrations.AddField(
            model_name='about_details',
            name='Address',
            field=models.TextField(default='H-11 Kitiyani, Mandsaur(M.P.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='name_of_project',
            field=models.CharField(default=3, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='year_made',
            field=models.CharField(default=4, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_link',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_certificate', models.CharField(max_length=56)),
                ('year_achived', models.CharField(max_length=32)),
                ('about_certificate', models.TextField()),
                ('certificate_link', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile_details')),
            ],
        ),
        migrations.CreateModel(
            name='achivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_achivement', models.CharField(max_length=56)),
                ('year', models.CharField(max_length=32)),
                ('about_achivement', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile_details')),
            ],
        ),
    ]
