# Generated by Django 3.0.7 on 2020-06-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0008_auto_20200630_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_details',
            name='Image',
            field=models.ImageField(default=2, upload_to='media'),
            preserve_default=False,
        ),
    ]
