# Generated by Django 3.0.7 on 2020-06-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0009_about_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_details',
            name='Image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
